CREATE TABLE CEP_INFO (
    cep CHAR(8) PRIMARY KEY,
    rua VARCHAR2(255) NOT NULL,
    bairro VARCHAR2(255) NOT NULL,
    cidade VARCHAR2(255) NOT NULL,
    estado CHAR(2) NOT NULL
);

CREATE TABLE Usuario (
    cpf CHAR(11) PRIMARY KEY,
    email VARCHAR2(255) UNIQUE NOT NULL,
    nome VARCHAR2(255) NOT NULL,
    descricao CLOB,
    cep CHAR(8) NOT NULL,
    numero_endereco VARCHAR2(20) NOT NULL,
    FOREIGN KEY (cep) REFERENCES CEP_INFO(cep)
);

CREATE TABLE Dados_Bancarios (
    usuario_cpf CHAR(11) PRIMARY KEY,
    banco VARCHAR2(50) NOT NULL,
    agencia VARCHAR2(20) NOT NULL,
    conta VARCHAR2(30) NOT NULL,
    FOREIGN KEY (usuario_cpf) REFERENCES Usuario(cpf) ON DELETE CASCADE
);

CREATE TABLE Telefone (
    usuario_cpf CHAR(11),
    telefone VARCHAR2(20),
    PRIMARY KEY (usuario_cpf, telefone),
    FOREIGN KEY (usuario_cpf) REFERENCES Usuario(cpf) ON DELETE CASCADE
);

CREATE TABLE Categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_categoria VARCHAR2(100) NOT NULL,
    descricao_categoria CLOB
);

CREATE TABLE Canal (
    id_canal NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_canal VARCHAR2(255) NOT NULL,
    data_criacao_canal DATE NOT NULL,
    descricao_canal CLOB
);

CREATE TABLE Espectador (
    cpf_espectador CHAR(11) PRIMARY KEY,
    FOREIGN KEY (cpf_espectador) REFERENCES Usuario(cpf) ON DELETE CASCADE
);

CREATE TABLE Streamer (
    cpf_streamer CHAR(11) PRIMARY KEY,
    id_canal NUMBER UNIQUE NOT NULL,
    FOREIGN KEY (cpf_streamer) REFERENCES Usuario(cpf) ON DELETE CASCADE,
    FOREIGN KEY (id_canal) REFERENCES Canal(id_canal) ON DELETE CASCADE
);

CREATE TABLE Transmissao (
    id_transmissao NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    status VARCHAR2(20),
    data_hora_inicio TIMESTAMP,
    data_hora_termino TIMESTAMP,
    canal_id NUMBER NOT NULL,
    max_espectadores_simultaneos NUMBER,
    FOREIGN KEY (canal_id) REFERENCES Canal(id_canal) ON DELETE CASCADE
);

CREATE TABLE Video (
    id_video NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    descricao CLOB,
    duracao_data_upload DATE,
    canal_id NUMBER NOT NULL,
    FOREIGN KEY (canal_id) REFERENCES Canal(id_canal) ON DELETE CASCADE
);

CREATE TABLE Clipe (
    usuario_cpf CHAR(11),
    id_transmissao NUMBER,
    data_criacao_clipe TIMESTAMP,
    titulo_clipe VARCHAR2(255) NOT NULL,
    tempo_clipe NUMBER NOT NULL,
    PRIMARY KEY (usuario_cpf, id_transmissao, data_criacao_clipe),
    FOREIGN KEY (usuario_cpf) REFERENCES Usuario(cpf),
    FOREIGN KEY (id_transmissao) REFERENCES Transmissao(id_transmissao)
);

CREATE TABLE Indica (
    indicador_cpf CHAR(11),
    indicado_cpf CHAR(11),
    data_indicacao DATE NOT NULL,
    comentario CLOB,
    PRIMARY KEY (indicador_cpf, indicado_cpf),
    FOREIGN KEY (indicador_cpf) REFERENCES Usuario(cpf) ON DELETE CASCADE,
    FOREIGN KEY (indicado_cpf) REFERENCES Usuario(cpf) ON DELETE CASCADE
);

CREATE TABLE Assina (
    usuario_cpf CHAR(11),
    canal_id NUMBER,
    nivel_assinatura VARCHAR2(50),
    data_inicio DATE NOT NULL,
    data_fim DATE,
    PRIMARY KEY (usuario_cpf, canal_id),
    FOREIGN KEY (usuario_cpf) REFERENCES Usuario(cpf),
    FOREIGN KEY (canal_id) REFERENCES Canal(id_canal)
);

CREATE TABLE Tem_Categoria (
    canal_id NUMBER,
    categoria_id NUMBER,
    PRIMARY KEY (canal_id, categoria_id),
    FOREIGN KEY (canal_id) REFERENCES Canal(id_canal),
    FOREIGN KEY (categoria_id) REFERENCES Categoria(id_categoria)
);

CREATE TABLE Avalia (
    espectador_cpf CHAR(11),
    transmissao_id NUMBER,
    nota NUMBER(2),
    comentario CLOB,
    PRIMARY KEY (espectador_cpf, transmissao_id),
    FOREIGN KEY (espectador_cpf) REFERENCES Espectador(cpf_espectador),
    FOREIGN KEY (transmissao_id) REFERENCES Transmissao(id_transmissao)
);

CREATE TABLE Segue (
    usuario_cpf CHAR(11),
    canal_id NUMBER,
    PRIMARY KEY (usuario_cpf, canal_id),
    FOREIGN KEY (usuario_cpf) REFERENCES Usuario(cpf),
    FOREIGN KEY (canal_id) REFERENCES Canal(id_canal)
);

CREATE TABLE Assiste (
    usuario_cpf CHAR(11),
    video_id NUMBER,
    data_assistido TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (usuario_cpf, video_id),
    FOREIGN KEY (usuario_cpf) REFERENCES Usuario(cpf),
    FOREIGN KEY (video_id) REFERENCES Video(id_video)
);

CREATE TABLE Acompanha (
    usuario_cpf CHAR(11),
    transmissao_id NUMBER,
    PRIMARY KEY (usuario_cpf, transmissao_id),
    FOREIGN KEY (usuario_cpf) REFERENCES Usuario(cpf),
    FOREIGN KEY (transmissao_id) REFERENCES Transmissao(id_transmissao)
);